# Generated by Django 5.1.1 on 2024-10-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_picture_tags_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='user',
        ),
    ]
